components {
  id: "enemy1"
  component: "/main/scripts/enemy1.script"
}
embedded_components {
  id: "enemy"
  type: "sprite"
  data: "default_animation: \"enemyy2.0\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/assets/main.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemy\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 1.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      y: -5.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -53.0\n"
  "      y: -25.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 4\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -53.0\n"
  "      y: 10.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 7\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 53.0\n"
  "      y: 10.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 10\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 53.0\n"
  "      y: -25.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 13\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 41.0\n"
  "      y: -36.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 16\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -40.0\n"
  "      y: -36.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 19\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -17.0\n"
  "      y: -36.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 22\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 17.0\n"
  "      y: -36.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 25\n"
  "    count: 3\n"
  "  }\n"
  "  data: 48.256\n"
  "  data: 31.67928\n"
  "  data: 48.256\n"
  "  data: 110.482086\n"
  "  data: 6.040273\n"
  "  data: 11.331812\n"
  "  data: 48.256\n"
  "  data: 6.040273\n"
  "  data: 11.331812\n"
  "  data: 48.256\n"
  "  data: 6.040273\n"
  "  data: 11.331812\n"
  "  data: 48.256\n"
  "  data: 6.040273\n"
  "  data: 11.331812\n"
  "  data: 48.256\n"
  "  data: 7.174329\n"
  "  data: 3.87141\n"
  "  data: 48.256\n"
  "  data: 7.174329\n"
  "  data: 3.87141\n"
  "  data: 48.256\n"
  "  data: 8.994325\n"
  "  data: 3.87141\n"
  "  data: 48.256\n"
  "  data: 8.994325\n"
  "  data: 3.87141\n"
  "  data: 48.256\n"
  "}\n"
  ""
}
