function on_message(self, message_id, message, sender)
	if message_id == hash("update_points") then
		gui.set_text(gui.get_node("points"), "Points - " .. message.value)

	elseif message_id == hash("update_missions") then
		local final_text = ""

		for i, m in ipairs(message.list) do
			local state = m.finished and "[Done] " or "[    ] "
			final_text = final_text .. state .. m.text .. "\n"
		end

		gui.set_text(gui.get_node("missions"), final_text)
	elseif message_id == hash("flash_alerta") then
		flash_alerta()
	elseif message_id == hash("flash_complete") then
		flash_complete()
	end
end

function flash_alerta()
	local node = gui.get_node("box")
	gui.set_color(node, vmath.vector4(1, 1, 1, 1))
	gui.animate(node, "color.w", 0, gui.EASING_OUT, 0.75)
end
function flash_complete()
	local node = gui. get_node("bux")
	gui.set_color(node, vmath.vector4(0, 1, 0, 0.5))
	gui.animate(node, "color.w", 0, gui.EASING_OUTBOUNCE, 1)
end