go.property("speed", 200)--propriedade de velocidade

function init(self)
	self.vel =  vmath.vector3(0,0,0)
	self.input = {
		up = false,
		down = false,
		left = false,
		right = false	-- a direção
	}
	msg.post(".", "acquire_input_focus")
	self.missions = {
		{text = "Get aces", finished = false, points = 100},
		{text = "Get out of zone", finished = false, points = 200}

	}
	self.points = 0
	self.aces_collected = 0
	self.total_aces = 5
	isSoundPlaying = false
	wall_sound = false
	enemy_attack = false
	--missões e pontos no início
	msg.post("/missions1#missions", "update_points", { value = self.points})
	msg.post("/missions1#missions", "update_missions", { list = self.missions})
end


function update(self, dt)
	-- Atualiza a direção com base nas teclas premidas
	local dir = vmath.vector3(0,0,0)
	if self.input.left then dir.x = dir.x - 1 end
	if self.input.right then dir.x = dir.x + 1 end
	if self.input.up then dir.y = dir.y + 1 end
	if self.input.down then dir.y = dir.y - 1 end

	-- Se houver movimento (dir ≠ 0), normaliza e atualiza a posição
	if dir.x ~= 0 or dir.y ~= 0 then
		dir = vmath.normalize(dir) -- normaliza para manter velocidade constante
		go.set_position(go.get_position() + dir * self.speed * dt) -- move o objeto
	end
end
function on_input(self, action_id, action)
	--input da tecla "left"
	if action_id == hash("left") then
		if action.pressed then
			self.input.left = true --ativa o movimento para a esquerda
		elseif action.released then
			self.input.left = false --desativa o movimetno para a esquerda
		end
	end
	--input da tecla "right"
	if action_id == hash("right") then
		if action.pressed then
			self.input.right = true --ativa o movimento para a direita
		elseif action.released then
			self.input.right = false --desativa o movimento para a direita
		end
	end
	--input da tecla "up"
	if action_id == hash("up") then
		if action.pressed then
			self.input.up = true --ativa o movimento para a direita
		elseif action.released then
			self.input.up = false --desativa o movimento para a direita
		end
	end
	--input da tecla "down"
	if action_id == hash("down") then
		if action.pressed then
			self.input.down = true --ativa o movimento para a direita
		elseif action.released then
			self.input.down = false --desativa o movimento para a direita
		end
	end
	local move = self.input.left or self.input.right or self.input.down or self.input.up 
	if move and not isSoundPlaying then
		sound.play("#footsteps")
		isSoundPlaying = true
	elseif isSoundPlaying and not move then
		sound.stop("#footsteps")
		isSoundPlaying = false
	end
end 
function finished_mission(self, index)
	if not self.missions[index].finished then
		self.missions[index].finished = true
		self.points = self.points + self.missions[index].points
		msg.post("/missions1#missions", "update_points", { value = self.points})
		msg.post("/missions1#missions", "update_missions", { list = self.missions})
	end
end

function on_message(self, message_id, message, sender, action_id)
	if message_id == hash("contact_point_response") then
		sound.play("#bonk")
		if message.normal.y > 0.1 then
			self.input.down = false
		end
		if message.normal.y < 0.1 then
			self.input.up = false

		end
		if message.normal.x > 0.1 then
			self.input.left = false

		end
		if message.normal.x < 0.1 then
			self.input.right = false
		end
		local pos = go.get_position()
		go.set_position(vmath.vector3(pos.x, pos.y, 0))
	end

	if message_id == hash("trigger_response") and message.enter then
		--colisão com o objeto
		if message.other_group == hash("ace") then
			go.delete(message.other_id)
			self.aces_collected = self.aces_collected + 1
			if self.aces_collected == self.total_aces then
				finished_mission(self,1) --missão 1 concluída
			end
		end
		--colisão com a porta
		if message.other_group == hash("door") then
			if self.missions[1].finished then
				finished_mission(self,2) -- missão 2 concluída
			end
		end
		--colisão do inimigo
		if message.other_group == hash("enemy") then
			print("jogador detectado")
			sound.play("#fx")
		end
		end
	end