local GameManager = require("main.scripts.GameManager")

local pending_scene = nil

local function switch_to_scene(new_scene)
	if new_scene == "game" then
		GameManager.current_level = new_scene
		msg.post("#menu", "unload")
		pending_scene = "#game"
	elseif new_scene == "credits" then
		GameManager.current_level = new_scene
		msg.post("#menu", "unload")
		msg.post("#cradits", "load")
	elseif new_scene == "exit" then
		sys.exit(0)
	end
end
function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#menu", "load")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "init")
		msg.post(sender, "enable")
	end
	if message_id == hash("proxy_unloaded") then
		-- Agora é seguro carregar a próxima cena
		if pending_scene then
			msg.post(pending_scene, "load")
			pending_scene = nil
		end
	end
	if message_id == hash("change_scene") and message.scene then
		switch_to_scene(message.scene)
	end
end